runtime: python39
instance_class: F2

env_variables:
  GOOGLE_SEARCH_API_KEY: "AIzaSyDSCmFmjPX1OdBQ3Ro4qSC3C6skEB0nI-o"
  GOOGLE_SEARCH_CX: "a3a26a1f03cc84ea4"
  GEMINI_API_KEY: "AIzaSyBskDBQaG0U6GO4jyGMyGTtgke2yYMBm5Q"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

entrypoint: gunicorn -b :$PORT app:create_app()
