services:
  - type: web
    name: car-ai-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r car-ai-backend/requirements.txt
    startCommand: gunicorn app:app --chdir car-ai-backend
    workingDir: car-ai-backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
