services:
  - type: web
    name: car-ai-backend
    env: python
    region: oregon
    plan: free
    branch: main
    workingDir: car-ai-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
