services:
  - type: web
    name: car-ai-backend
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
