services:
  - type: web
    name: car-ai-backend
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn backend_app:app  # ← CHỈ nếu app.py có dòng `app = Flask(__name__)`
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
